language: scala
scala:
   - "2.10.4"
jdk:
   - oraclejdk7
   - openjdk7
before_install:
  - export SBT_OPTS="-Xms1536m -Xmx1536m -XX:MaxPermSize=384m -XX:ReservedCodeCacheSize=192m"
  - ./build_piper.sh
install: ./install_piper.sh
